const vocabulary = {
  schule: [
    { kr: '학교', de: 'Schule' },
    { kr: '학생', de: 'Schüler' },
    { kr: '수업', de: 'Unterricht' },
    { kr: '선생님', de: 'Lehrer' },
    { kr: '교실', de: 'Klassenzimmer' },
    { kr: '책', de: 'Buch' },
    { kr: '연필', de: 'Bleistift' },
    { kr: '시험', de: 'Prüfung' },
    { kr: '숙제', de: 'Hausaufgabe' },
    { kr: '칠판', de: 'Tafel' }
  ],
  obst: [
    { kr: '사과', de: 'Apfel' },
    { kr: '바나나', de: 'Banane' },
    { kr: '오렌지', de: 'Orange' },
    { kr: '포도', de: 'Traube' },
    { kr: '딸기', de: 'Erdbeere' },
    { kr: '수박', de: 'Wassermelone' },
    { kr: '복숭아', de: 'Pfirsich' },
    { kr: '자두', de: 'Pflaume' },
    { kr: '체리', de: 'Kirsche' },
    { kr: '레몬', de: 'Zitrone' }
  ],
  gemuese: [
    { kr: '당근', de: 'Karotte' },
    { kr: '감자', de: 'Kartoffel' },
    { kr: '토마토', de: 'Tomate' },
    { kr: '양파', de: 'Zwiebel' },
    { kr: '마늘', de: 'Knoblauch' },
    { kr: '오이', de: 'Gurke' },
    { kr: '상추', de: 'Salat' },
    { kr: '시금치', de: 'Spinat' },
    { kr: '버섯', de: 'Pilz' },
    { kr: '호박', de: 'Kürbis' }
  ],
  tiere: [
    { kr: '개', de: 'Hund' },
    { kr: '고양이', de: 'Katze' },
    { kr: '새', de: 'Vogel' },
    { kr: '말', de: 'Pferd' },
    { kr: '소', de: 'Kuh' },
    { kr: '돼지', de: 'Schwein' },
    { kr: '토끼', de: 'Kaninchen' },
    { kr: '사자', de: 'Löwe' },
    { kr: '코끼리', de: 'Elefant' },
    { kr: '물고기', de: 'Fisch' }
  ],
  familie: [
    { kr: '어머니', de: 'Mutter' },
    { kr: '아버지', de: 'Vater' },
    { kr: '형제', de: 'Bruder' },
    { kr: '자매', de: 'Schwester' },
    { kr: '아들', de: 'Sohn' },
    { kr: '딸', de: 'Tochter' },
    { kr: '할아버지', de: 'Großvater' },
    { kr: '할머니', de: 'Großmutter' },
    { kr: '부모님', de: 'Eltern' },
    { kr: '가족', de: 'Familie' }
  ],
  kleidung: [
    { kr: '셔츠', de: 'Hemd' },
    { kr: '바지', de: 'Hose' },
    { kr: '신발', de: 'Schuhe' },
    { kr: '모자', de: 'Hut' },
    { kr: '양말', de: 'Socken' },
    { kr: '치마', de: 'Rock' },
    { kr: '코트', de: 'Mantel' },
    { kr: '드레스', de: 'Kleid' },
    { kr: '재킷', de: 'Jacke' },
    { kr: '벨트', de: 'Gürtel' }
  ],
  zuhause: [
    { kr: '집', de: 'Haus' },
    { kr: '방', de: 'Zimmer' },
    { kr: '부엌', de: 'Küche' },
    { kr: '욕실', de: 'Badezimmer' },
    { kr: '거실', de: 'Wohnzimmer' },
    { kr: '창문', de: 'Fenster' },
    { kr: '문', de: 'Tür' },
    { kr: '침대', de: 'Bett' },
    { kr: '소파', de: 'Sofa' },
    { kr: '식탁', de: 'Esstisch' }
  ],
  essen: [
    { kr: '빵', de: 'Brot' },
    { kr: '밥', de: 'Reis' },
    { kr: '물', de: 'Wasser' },
    { kr: '커피', de: 'Kaffee' },
    { kr: '차', de: 'Tee' },
    { kr: '고기', de: 'Fleisch' },
    { kr: '생선', de: 'Fisch' },
    { kr: '치즈', de: 'Käse' },
    { kr: '우유', de: 'Milch' },
    { kr: '주스', de: 'Saft' }
  ],
  koerper: [
    { kr: '머리', de: 'Kopf' },
    { kr: '눈', de: 'Auge' },
    { kr: '손', de: 'Hand' },
    { kr: '발', de: 'Fuß' },
    { kr: '귀', de: 'Ohr' },
    { kr: '코', de: 'Nase' },
    { kr: '입', de: 'Mund' },
    { kr: '다리', de: 'Bein' },
    { kr: '팔', de: 'Arm' },
    { kr: '목', de: 'Hals' }
  ],
  farben: [
    { kr: '빨강', de: 'Rot' },
    { kr: '파랑', de: 'Blau' },
    { kr: '노랑', de: 'Gelb' },
    { kr: '초록', de: 'Grün' },
    { kr: '검정', de: 'Schwarz' },
    { kr: '흰색', de: 'Weiß' },
    { kr: '회색', de: 'Grau' },
    { kr: '분홍', de: 'Rosa' },
    { kr: '주황', de: 'Orange' },
    { kr: '갈색', de: 'Braun' }
  ],
  berufe: [
    { kr: '의사', de: 'Arzt' },
    { kr: '간호사', de: 'Krankenschwester' },
    { kr: '선생님', de: 'Lehrer' },
    { kr: '경찰관', de: 'Polizist' },
    { kr: '요리사', de: 'Koch' },
    { kr: '엔지니어', de: 'Ingenieur' },
    { kr: '기자', de: 'Journalist' },
    { kr: '변호사', de: 'Anwalt' },
    { kr: '가수', de: 'Sänger' },
    { kr: '배우', de: 'Schauspieler' }
  ],
  reisen: [
    { kr: '비행기', de: 'Flugzeug' },
    { kr: '기차', de: 'Zug' },
    { kr: '버스', de: 'Bus' },
    { kr: '택시', de: 'Taxi' },
    { kr: '배', de: 'Schiff' },
    { kr: '여행', de: 'Reise' },
    { kr: '호텔', de: 'Hotel' },
    { kr: '지도', de: 'Karte' },
    { kr: '길', de: 'Straße' },
    { kr: '공항', de: 'Flughafen' }
  ],
  natur: [
    { kr: '비', de: 'Regen' },
    { kr: '눈', de: 'Schnee' },
    { kr: '바람', de: 'Wind' },
    { kr: '태양', de: 'Sonne' },
    { kr: '구름', de: 'Wolke' },
    { kr: '산', de: 'Berg' },
    { kr: '강', de: 'Fluss' },
    { kr: '바다', de: 'Meer' },
    { kr: '숲', de: 'Wald' },
    { kr: '꽃', de: 'Blume' }
  ],
  zeit: [
    { kr: '오늘', de: 'Heute' },
    { kr: '어제', de: 'Gestern' },
    { kr: '내일', de: 'Morgen' },
    { kr: '시간', de: 'Zeit' },
    { kr: '날짜', de: 'Datum' },
    { kr: '주', de: 'Woche' },
    { kr: '달', de: 'Monat' },
    { kr: '해', de: 'Jahr' },
    { kr: '시계', de: 'Uhr' },
    { kr: '일요일', de: 'Sonntag' }
  ],
  adjektive: [
    { kr: '크다', de: 'groß' },
    { kr: '작다', de: 'klein' },
    { kr: '빠르다', de: 'schnell' },
    { kr: '느리다', de: 'langsam' },
    { kr: '춥다', de: 'kalt' },
    { kr: '덥다', de: 'heiß' },
    { kr: '쉽다', de: 'einfach' },
    { kr: '어렵다', de: 'schwierig' },
    { kr: '재미있다', de: 'interessant' },
    { kr: '친절하다', de: 'freundlich' }
  ],
  verben: [
    { kr: '먹다', de: 'essen' },
    { kr: '마시다', de: 'trinken' },
    { kr: '가다', de: 'gehen' },
    { kr: '오다', de: 'kommen' },
    { kr: '자다', de: 'schlafen' },
    { kr: '일어나다', de: 'aufstehen' },
    { kr: '읽다', de: 'lesen' },
    { kr: '쓰다', de: 'schreiben' },
    { kr: '보다', de: 'sehen' },
    { kr: '듣다', de: 'hören' }
  ],
  technologie: [
    { kr: '컴퓨터', de: 'Computer' },
    { kr: '인터넷', de: 'Internet' },
    { kr: '전화', de: 'Telefon' },
    { kr: '이메일', de: 'E-Mail' },
    { kr: '프로그램', de: 'Programm' },
    { kr: '앱', de: 'App' },
    { kr: '화면', de: 'Bildschirm' },
    { kr: '버튼', de: 'Knopf' },
    { kr: '데이터', de: 'Daten' },
    { kr: '로봇', de: 'Roboter' }
  ],
  sport: [
    { kr: '축구', de: 'Fußball' },
    { kr: '농구', de: 'Basketball' },
    { kr: '음악', de: 'Musik' },
    { kr: '그림', de: 'Malerei' },
    { kr: '춤', de: 'Tanz' },
    { kr: '영화', de: 'Film' },
    { kr: '게임', de: 'Spiel' },
    { kr: '독서', de: 'Lesen' },
    { kr: '달리기', de: 'Laufen' },
    { kr: '수영', de: 'Schwimmen' }
  ],
  medizin: [
    { kr: '병원', de: 'Krankenhaus' },
    { kr: '약', de: 'Medizin' },
    { kr: '건강', de: 'Gesundheit' },
    { kr: '의사', de: 'Arzt' },
    { kr: '약사', de: 'Apotheker' },
    { kr: '치료', de: 'Behandlung' },
    { kr: '운동', de: 'Bewegung' },
    { kr: '휴식', de: 'Ruhe' },
    { kr: '다이어트', de: 'Diät' },
    { kr: '스트레스', de: 'Stress' }
  ],
  gefuehle: [
    { kr: '기쁨', de: 'Freude' },
    { kr: '슬픔', de: 'Trauer' },
    { kr: '화', de: 'Wut' },
    { kr: '사랑', de: 'Liebe' },
    { kr: '두려움', de: 'Angst' },
    { kr: '욕심', de: 'Gier' },
    { kr: '부끄러움', de: 'Scham' },
    { kr: '놀람', de: 'Überraschung' },
    { kr: '지루함', de: 'Langeweile' },
    { kr: '행복', de: 'Glück' }
  ]
};
